apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-16T17:57:32Z"
  generation: 1
  labels:
    app: vue-app
  name: vue-app
  namespace: project
  resourceVersion: "271131"
  uid: 29474a89-a26c-488e-9ab6-27fb00bfdfb6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vue-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vue-app
    spec:
      containers:
      - image: malikdevops/vue-project:latest
        imagePullPolicy: Always
        name: vue-project
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-16T17:57:38Z"
    lastUpdateTime: "2023-11-16T17:57:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-16T17:57:32Z"
    lastUpdateTime: "2023-11-16T17:57:38Z"
    message: ReplicaSet "vue-app-55d8456f8d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
